version: '3.8'
services:
  postgres:
    image: "postgres"
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "ginger"
      POSTGRES_DB: "ginger"

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '63791:6379'
    command: redis-server --save 20 1 --loglevel warning